name: Java CI

on:
  push:
    branches: 
      - master
  schedule:
    - cron:  "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Shanghai Weather Report
        body: file://result.html
        to: emmawang1990@outlook.com
        from: GitHub Actions
        content_type: text/html
